[[templates]]
name = "Cargo"
file = "files/cargo.sh"
language = "sh"

[[templates]]
name = "compose.yml"
file = "files/compose.yml"
output = "compose.yml"
language = "yaml"

[[templates]]
name = "buildx quickfix"
file = "files/docker-buildx.sh"
language = "sh"

[[templates]]
name = "Dockerfile - ubuntu"
file = "files/Dockerfile.ubuntu"
language = "Dockerfile"

[[templates]]
name = "nginx"
file = "files/default.conf"
language = "nginx"

[[templates]]
name = "Apt proxy"
file = "files/apt.conf"
language = "sh"
clipboard = true

[[templates]]
name = "k8s proxy"
file = "files/k8s-proxy.sh"
language = "sh"

[[templates]]
name = "k8s statefulset"
file = "files/k8s-statefulset.yml"
language = "yaml"
lua = { file = "lua/k8s.lua" }

[[templates]]
name = "RKE2 openebs"
file = "files/rke2-openebs.sh"
language = "sh"

[[templates]]
name = "LVM"
file = "files/lvm.sh"
language = "sh"

