[[templates]]
name = "compose.yml"
file = "files/compose.yml"
language = "yaml"

[[templates]]
name = "Docker daemon.json"
file = "files/daemon.json"
language = "json"

[[templates]]
name = "Dockerfile - ubuntu"
file = "files/Dockerfile.ubuntu"
language = "Dockerfile"

[[templates]]
name = "nginx"
file = "files/default.conf"
language = "nginx"

[[templates]]
name = "Apt proxy"
file = "files/apt.conf"
language = "sh"
clipboard = true

[[templates]]
name = "k8s statefulset"
file = "files/k8s-statefulset.yml"
language = "yaml"
lua = { file = "lua/k8s.lua" }

[[templates]]
name = "k8s dashboard"
file = "files/k8s-dashboard.sh"
language = "sh"
lua = { file = "lua/no-commented-line.lua" }
clipboard = true