#!/bin/sh
# shellcheck shell=dash

# This script assume that the current working directory is set to git working directory

set -e

cat zsh/src/zshrc/*.zsh > zsh/.zshrc
cat zsh/src/zprofile/*.zsh > zsh/.zprofile.merged.zsh

