[package]
name = "nmk"
version = "0.1.0"
authors = ["Nui Narongwet <narongwet.m@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
common = {path = "../common", version = "0.1.0"}
dirs = "2.0.2"
indexmap = "1.3.0"
log = "0.4.8"
nix = "0.16.0"
simplelog = "0.7.4"
which = "3.1.0"
