steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -e
    - 'GIT_SHORT_SHA=$SHORT_SHA'
    - -v=/workspace:/workspace
    - --workdir=/workspace/nmkup
    - 'gcr.io/$PROJECT_ID/nmk.rs'
    - make
    - show-build-info
    - test
    - amd64-linux-musl
    - armv7-linux
    - dist
  timeout: 1200s
artifacts:
  objects:
    location: "gs://nmk.nuimk.com/nmk.rs"
    paths:
      - nmk-amd64-linux-musl.gz
      - nmk-armv7-linux.gz
      - nmkup-amd64-linux-musl
      - nmkup-armv7-linux
timeout: 1500s
options:
  machineType: 'N1_HIGHCPU_8'
