steps:
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'gs://nuimk-io-build-cache/nmk.rs/target.tar.gz', 'target.tar.gz']
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'gs://nuimk-io-build-cache/nmk.rs/cargo-registry.tar.gz', 'cargo-registry.tar.gz']
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     - run
#     - -v=/workspace:/workspace
#     - -v=/workspace/cargo-build-cache-dir:/cargo-build-cache-dir
#     - --workdir=/workspace
#     - 'gcr.io/$PROJECT_ID/nmk.rs'
#     - ./docker/nmk.rs/restore-gcloud-cache
#   timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -e
    - 'GIT_SHORT_SHA=$SHORT_SHA'
    - -v=/workspace:/workspace
    # - -v=/workspace/cargo-build-cache-dir/registry:/root/.cargo/registry
    - --workdir=/workspace/nmk.rs
    - 'gcr.io/$PROJECT_ID/nmk.rs'
    - make
    - show-build-info
    - test
    - amd64-linux-musl
    - armv7-linux
    - dist
  timeout: 1200s
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#     - run
#     - -v=/workspace:/workspace
#     - -v=/workspace/cargo-build-cache-dir:/cargo-build-cache-dir
#     - --workdir=/workspace
#     - 'gcr.io/$PROJECT_ID/nmk.rs'
#     - ./docker/nmk.rs/save-gcloud-cache
#   timeout: 180s
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'target.tar.gz', 'gs://nuimk-io-build-cache/nmk.rs/target.tar.gz']
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'cargo-registry.tar.gz', 'gs://nuimk-io-build-cache/nmk.rs/cargo-registry.tar.gz']
artifacts:
  objects:
    location: "gs://nmk.nuimk.com/nmk.rs"
    paths:
      - nmk-amd64-linux-musl.gz
      - nmk-armv7-linux.gz
      - nmkup-amd64-linux-musl
      - nmkup-armv7-linux
timeout: 1500s
options:
  machineType: 'N1_HIGHCPU_8'
