FROM ubuntu:24.04

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -yq update \
    && apt-get -yq upgrade \
    && apt-get -yq --no-install-recommends install \
        git \
    && rm -rf /var/lib/apt/lists/*
