version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: nuimk/nmkpkg:centos-6.10
    entrypoint: /bin/bash
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: nuimk/nmkpkg:alpine

  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: nuimk/nmkpkg:builder

