version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: nuimk/nmkpkg:centos-6.9
    entrypoint: /bin/bash
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: nmk:python

