steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -f
    - docker/nmk.go/Dockerfile
    - -t
    - builder
    - .
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -f
    - docker/nmk.go/Dockerfile.alpine
    - -t
    - builder-alpine
    - .
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -v
    - /workspace:/workspace
    - builder
    - sh
    - -c
    - cp /go/build/* /workspace
  timeout: 60s
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - -v
    - /workspace:/workspace
    - builder-alpine
    - sh
    - -c
    - cp /go/build/* /workspace
  timeout: 60s
artifacts:
  objects:
    location: "gs://nmk.nuimk.com/nmk.go"
    paths:
      - nmk.go-amd64-darwin
      - nmk.go-amd64-freebsd
      - nmk.go-amd64-linux
      - nmk.go-amd64-linux-musl
      - nmk.go-arm-linux
      - nmk.go-arm64-linux

