[package]
name = "nmkrs"
version = "1.0.0"
authors = ["Nui Narongwet <narongwet.m@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4.7"
stderrlog = "0.4.1"
dirs = "2.0.1"
which = "2.0.1"
nix = "0.14.1"
serde_json = "1.0.40"
serde = { version = "1.0.97", features = ["derive"] }
