[package]
name = "nmkrs"
version = "1.0.0"
authors = ["Nui Narongwet <narongwet.m@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4"
stderrlog = "0.4"
dirs = "2.0.0"
which = "2.0.1"
nix = "0.14.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
