[[templates]]
name = "compose.yml"
file = "compose.yml"
output = "compose.yml"
language = "yaml"
middlewares = [
    { name = "text", args = ["random"] }
]

[[templates]]
name = "Dockerfile - ubuntu"
file = "Dockerfile.ubuntu"
language = "Dockerfile"

[[templates]]
name = "nginx"
file = "default.conf"
language = "nginx"

[[templates]]
name = "k8s statefulset"
file = "k8s-statefulset.yml"
language = "yaml"
middlewares = [
    { name = "text", args = ["no-comment"] },
]

[[templates]]
name = "k8s ingress-route.yaml"
file = "ingress-route.yaml"
language = "yaml"

