#!/bin/sh
# This script is generated by chatgpt to get same result as rust std::thread::available_parallelism
# Linux only, no macOS support

# Number of CPUs available via affinity mask
affinity=$(nproc)
[ "$affinity" -lt 1 ] && affinity=1

quota_cpus=""

# Detect cgroup v2
if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
    cgpath=$(cut -d: -f3 /proc/self/cgroup)

    [ "$cgpath" = "/" ] && cpu_max="/sys/fs/cgroup/cpu.max" \
                        || cpu_max="/sys/fs/cgroup${cgpath}/cpu.max"

    if [ -r "$cpu_max" ]; then
        read quota period < "$cpu_max"
        if [ "$quota" != "max" ]; then
            quota_cpus=$(( (quota + period - 1) / period ))
        fi
    fi
else
    # cgroup v1
    cgpath=$(awk -F: '$2=="cpu" || $2=="cpu,cpuacct" {print $3}' /proc/self/cgroup)

    # Find the cpu controller mount point
    mountpoint=$(awk '$3=="cgroup" && $4 ~ /(^|,)cpu(,|$)/ {print $2; exit}' /proc/mounts)

    if [ -n "$mountpoint" ] && [ -n "$cgpath" ]; then
        quota_file="$mountpoint$cgpath/cpu.cfs_quota_us"
        period_file="$mountpoint$cgpath/cpu.cfs_period_us"

        if [ -r "$quota_file" ] && [ -r "$period_file" ]; then
            quota=$(cat "$quota_file")
            period=$(cat "$period_file")

            if [ "$quota" -gt 0 ]; then
                quota_cpus=$(( (quota + period - 1) / period ))
            fi
        fi
    fi
fi

# Ensure at least one CPU
if [ -n "$quota_cpus" ] && [ "$quota_cpus" -lt 1 ]; then
    quota_cpus=1
fi

# Return min(affinity, quota)
if [ -n "$quota_cpus" ] && [ "$quota_cpus" -lt "$affinity" ]; then
    echo "$quota_cpus"
else
    echo "$affinity"
fi
