#!/usr/bin/env zsh

cd ${0:a:h}

(( ! ${+NMK_HOME} )) && {
    print -- '$NMK_HOME is unset'
    exit 1
}

ZSH_COMPLETE_DIR=$ZDOTDIR/completion
ZSH_DYNAMIC_COMPLETION_DIR=$ZDOTDIR/zshrc.clap-dynamic-completion.d

(( ${+commands[nbox]} )) && nbox completions zsh -o "$ZSH_COMPLETE_DIR/_nbox"
(( ${+commands[nmkup]} )) && {
    nmkup --write-zsh-completion "$ZSH_COMPLETE_DIR/_nmkup"
    COMPLETE=zsh nmkup > $ZSH_DYNAMIC_COMPLETION_DIR/nmkup.zsh
}
(( ${+commands[nmk]} )) && {
    nmk completions zsh -o "$ZSH_COMPLETE_DIR/_nmk"
    COMPLETE=zsh nmk > $ZSH_DYNAMIC_COMPLETION_DIR/nmk.zsh
}

