#!/usr/bin/env zsh

cd ${0:a:h}

(( ! ${+NMK_HOME} )) && {
    print -- '$NMK_HOME is unset'
    exit 1
}

ZSH_COMPLETE_DIR=$ZDOTDIR/completion

(( ${+commands[nmk]} )) && nmk completions zsh -o $ZSH_COMPLETE_DIR/_nmk
(( ${+commands[nbox]} )) && nbox completions zsh -o $ZSH_COMPLETE_DIR/_nbox

