#!/bin/zsh

set -e


if [ -z "$1" ]; then
    echo "Usage: $0 KEYCHAIN_ACCESS_SERVICE_NAME"
    exit 1
fi

if [ -z "$KUBECONFIG" ]; then
    echo "KUBECONFIG is unset"
    exit 1
fi

KEYCHAIN_ACCESS_SERVICE_NAME=$1

TOKEN=$(kubectl config view --raw -o json | jq '.users[] | select(.name=="default") | .user' -c)

echo $TOKEN

set -x

kubectl passman keychain $KEYCHAIN_ACCESS_SERVICE_NAME $TOKEN

kubectl config set-credentials default \
 --exec-api-version=client.authentication.k8s.io/v1beta1 \
 --exec-command=kubectl-passman \
 --exec-arg=keychain \
 --exec-arg=$KEYCHAIN_ACCESS_SERVICE_NAME

echo "Don't forget to remove client-certificate-data and client-key-data config"

