() {
    setopt localoptions noshwordsplit

    local script=$ZDOTDIR/zshrc.extra.d/10-init-fzf.zsh
    ((${+commands[fzf]})) && {
        # script file exist and has been modified within a day
        if [[ -e $script ]] && [[ -n $(find $script -maxdepth 0 -type f -mtime -1) ]]; then
            # do nothing
        else
            rm -f $script
            (
                print '### This file is generated by $NMK_HOME/zsh/template/zprofile.d/generate-init-fzf.zsh'
                print '###'
                fzf --zsh
            ) > $script
        fi
    }
}
