() {
    setopt localoptions noshwordsplit

    local script=$ZDOTDIR/zshrc.extra.d/10-fzf-shell-integration.zsh
    ((${+commands[fzf]})) && {
        
        # script file exist and has been modified within a day
        if [[ -e $script ]] && [[ -n $(find $script -maxdepth 0 -type f -mtime -1) ]]; then
            # do nothing
        else
            rm -f $script
            (
                print '# -- This file is generated by $NMK_HOME/zsh/template/zprofile.d/generate-init-fzf.zsh'
                print '#'
                print '# -- start of config --'
                # Use default value or set it to empty value
                print 'export FZF_CTRL_R_COMMAND=$FZF_CTRL_R_COMMAND'
                print '# -- end of config --'
                print '# -- below lines are from "fzf --zsh" output'
                fzf --zsh
            ) > $script
        fi
    }
}
