() {
    setopt localoptions noshwordsplit

    local script=$ZDOTDIR/zshrc.extra.d/10-fzf-shell-integration.zsh
    ((${+commands[fzf]})) && {
        # script file exist and has been modified within a day
        if [[ -e $script ]] && [[ -n $(find $script -maxdepth 0 -type f -mtime -1) ]]; then
            # do nothing
        else
            rm -f $script
            cat > $script <<'EOS'
# >> This file is generated by $NMK_HOME/zsh/template/zprofile.d/generate-fzf-shell-integration.zsh
# 
# Disable Ctrl-R integration by default
export FZF_CTRL_R_COMMAND=$FZF_CTRL_R_COMMAND
#
# >> Below lines are the output ofl "fzf --zsh"
EOS
        fzf --zsh >> $script
        fi
    }
}
