name: Build dotfiles tar

on:
  push:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Type of machine to run the job on
        required: true
        type: choice
        default: ubuntu-24.04
        options:
          - ubuntu-24.04

env:
  C_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_and_upload:
    runs-on: ${{ inputs.runs-on || 'ubuntu-24.04' }}
    name: Build dotfiles tarball

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: ghcr.io/${{ github.repository }}/workflow

    steps:
      - uses: actions/checkout@v5
      - name: Build tar file
        run: |
          set -ex
          rm -rf dist && mkdir dist
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          python3 etc/build.py --no-upload --branch "$branch" --copy-to dist
      - name: Sign output files
        shell: bash
        env:
          BINARY_SIGNING_KEY: ${{ secrets.BINARY_SIGNING_KEY }}
        run: |
          set -ex
          files=(dotfiles.tar.xz dotfiles.tar.xz.sha256)
          cd dist
          for file in ${files[@]}; do
            nmk ed25519 sign --key-env BINARY_SIGNING_KEY --file $file --output ${file}.sig
          done
      - name: Final artifact summary
        run: |
          set -e
          (
            echo '## Artifact files'
            echo '```sh'
            ls -lh dist
            echo '```'
          ) >> "$GITHUB_STEP_SUMMARY"
      - name: "Authenticate to google cloud"
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
      - name: 'Upload to public bucket'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: dist
          parent: false
          gzip: true
          destination: 'nmk.nuimk.com/channels/${{ env.C_BRANCH_NAME }}'
          process_gcloudignore: false
