name: Build dotfiles tar

on:
  push:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Type of machine to run the job on
        required: true
        type: choice
        default: ubuntu-24.04
        options:
          - ubuntu-24.04

env:
  C_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_and_upload:
    runs-on: ${{ inputs.runs-on || 'ubuntu-24.04' }}
    name: Build dotfiles tarball

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: ghcr.io/${{ github.repository }}/workflow

    steps:
      - uses: actions/checkout@v6
      - name: Build tar file
        run: |
          set -ex
          rm -rf dist && mkdir dist
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          python3 etc/build.py --no-upload --branch "$branch" --copy-to dist
      - name: Sign output files
        shell: bash
        env:
          BINARY_SIGNING_KEY: ${{ secrets.BINARY_SIGNING_KEY }}
        run: |
          set -ex
          files=(dotfiles.tar.xz)
          cd dist
          json_template=$(cat <<'EOF'
          {
            "name": $name,
            "github_ref_name": $github_ref_name,
            "signature": $signature
          }
          EOF
          )
          github_ref_name=${GITHUB_REF_NAME}
          for file in ${files[@]}; do
            sig_file=${file}.sig
            nmk ed25519 sign --key-env BINARY_SIGNING_KEY --file "$file" --output "$sig_file"
            signature=$(base64 -w 0 < "$sig_file")
            jq -n \
              --arg name "$file" \
              --arg github_ref_name "$github_ref_name" \
              --arg signature "$signature" \
              "$json_template" > "${file}".meta.json
            rm -f "$sig_file"
          done
      - name: Final artifact summary
        run: |
          set -e
          (
            echo '## Artifact files'
            echo '```sh'
            ls -lh dist
            echo '```'
          ) >> "$GITHUB_STEP_SUMMARY"
      - name: Upload to cloudflare R2
        uses: docker://amazon/aws-cli
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.CF_R2_NMK_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_NMK_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ vars.CF_R2_S3_API }}
          AWS_DEFAULT_REGION: auto
          SCRIPT: |-
            set -ex
            aws s3 cp dist/ s3://nmk/channels/${{ env.C_BRANCH_NAME}}/ --recursive --include '*'
        with:
          entrypoint: "/bin/sh"
          args: -c "eval \"$SCRIPT\""
      - name: Purge cloudflare cache
        env:
          ZONE_ID: ${{ vars.CF_NUIMK_COM_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_NUIMK_DOT_COM_API_TOKEN }}
        run: |
          set -x
          request_body=$(
            jq -n \
              --arg prefix "nmk-files.nuimk.com/channels/${{ env.C_BRANCH_NAME}}/dotfiles" \
              '{"prefixes":[$prefix]}'
            )
          # perge cache by prefixes
          curl https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache \
              -H 'Content-Type: application/json' \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -d "$request_body"

