name: Build and publish dotfiles ubuntu image

on:
  schedule:
    # Daily at midnight
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      runs-on:
        description: Type of machine to run the job on
        required: true
        type: choice
        default: ubuntu-24.04
        options:
          - ubuntu-24.04

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ${{ inputs.runs-on || 'ubuntu-24.04' }}
    name: Build and publish

    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    steps:
      - uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-ubuntu
            type=ref,event=tag,suffix=-ubuntu
            type=ref,event=pr,suffix=-ubuntu
            # set latest tag for default branch
            type=raw,value=ubuntu,enable={{is_default_branch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build and export docker image
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.dotfiles
          target: dotfiles-ubuntu
          pull: true
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
